[versions]

asm = '9.8'

[libraries]
jetbrains-annotations = 'org.jetbrains:annotations:26.0.2'
google-autoservice = 'com.google.auto.service:auto-service:1.1.1'

asm = { group = 'org.ow2.asm', name = 'asm', version.ref = 'asm' }
asm-tree = { group = 'org.ow2.asm', name = 'asm-tree', version.ref = 'asm' }
asm-commons = { group = 'org.ow2.asm', name = 'asm-commons', version.ref = 'asm' }
asm-util = { group = 'org.ow2.asm', name = 'asm-util', version.ref = 'asm' }

